name: Simple CI Pipeline

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check file
        run: |
          if [ -f app.txt ]; then
            echo "File exists"
          else
            echo "Missing file"
          fi

  build:
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Build step
        run: echo "building project"

  info:
    needs: build
    runs-on: ubuntu-latest


    steps:
      - name: Final step
        run: echo "pipeline completed"
