name: Real CI Pipeline

on: [push]

env:
  PROJECT_NAME: DevOps-CI

jobs:

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file exists
        run: |
          if [ -f app.txt ]; then
            echo "File exists"
          else
            echo "Missing file"
            exit 1
          fi

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Build step
        run: echo "Building $PROJECT_NAME"

      - name: Create artifact file
        run: echo "Build completed for $PROJECT_NAME" > result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: result.txt

  report:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Show result
        run: cat result.txt
