name: Self Hosted Runner Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check runner
        run: |
          echo "Running on self-hosted runner"
          hostname
          uname -a
